Update patch set 2
Patch Set 2:

Executing: ['/bin/bash', '-c', 'git cherry-pick -Xpatience --keep-redundant-commits FETCH_HEAD'] from /mnt/disks/build-disk/src/googleplex-android/master/frameworks/base
error: could not apply 9831a2d... Depend on the stable AIDL version of the netd metrics interface.
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'

Patch-set: 2
Reviewer: Gerrit User 1000835 <1000835@85c56323-6fa9-3386-8a01-6480fb634889>