Update patch set 3
Patch Set 3: Presubmit-Verified-1

=== Finished presubmit run: L71000000076637636 ===

FAIL: Some checks failed. See below.


=== aosp-master/aosp_arm64-eng ===

PASS: Built aosp-master/aosp_arm64-eng/4124990 (ToT). See https://android-build.googleplex.com/builds/pending/P4481739/aosp_arm64-eng/latest


=== aosp-master/aosp_x86-eng ===

PASS: Built aosp-master/aosp_x86-eng/4124990 (ToT). See https://android-build.googleplex.com/builds/pending/P4481733/aosp_x86-eng/latest


=== git_master/bullhead-userdebug_fastbuild3a_linux ===

CONFLICT: Your changes failed to cherry-pick against build 4125040 (\'ETIMEDOUT\' was not declared in this scope".). See logs/git.log in https://android-build.googleplex.com/builds/pending/P4481736/bullhead-userdebug_fastbuild3a_linux/latest. NOTE: This build has automerged changes. You may need to perform a manual  merge. See http://go/automerger-presubmit-faq

SKIPPED: Tests were skipped for git_master/bullhead-userdebug_fastbuild3a_linux/4125040 (ToT). Internal error: cannot find a successful build output for target bullhead-userdebug_fastbuild3a_linux

SKIPPED: Tests were skipped for git_master/bullhead-userdebug_fastbuild3a_linux/4125040 (ToT). Internal error: cannot find a successful build output for target bullhead-userdebug_fastbuild3a_linux

SKIPPED: Tests were skipped for git_master/bullhead-userdebug_fastbuild3a_linux/4125040 (ToT). Internal error: cannot find a successful build output for target bullhead-userdebug_fastbuild3a_linux

SKIPPED: Tests were skipped for git_master/bullhead-userdebug_fastbuild3a_linux/4125040 (ToT). Internal error: cannot find a successful build output for target bullhead-userdebug_fastbuild3a_linux


=== git_master/errorprone_fastbuild3e_linux ===

CONFLICT: Your changes failed to cherry-pick against build 4125040 (could not apply 0169376... Clean up Predicate related code in android.test). See logs/git.log in https://android-build.googleplex.com/builds/pending/P4481737/errorprone_fastbuild3e_linux/latest. NOTE: This build has automerged changes. You may need to perform a manual  merge. See http://go/automerger-presubmit-faq


=== git_master/gce_x86_phone-userdebug_fastbuild3c_linux ===

CONFLICT: Your changes failed to cherry-pick against build 4125040 (could not apply 0169376... Clean up Predicate related code in android.test). See logs/git.log in https://android-build.googleplex.com/builds/pending/P4481735/gce_x86_phone-userdebug_fastbuild3c_linux/latest. NOTE: This build has automerged changes. You may need to perform a manual  merge. See http://go/automerger-presubmit-faq

CONFLICT: Your changes failed to cherry-pick against build 4125040 (could not apply 0169376... Clean up Predicate related code in android.test). See logs/git.log in https://android-build.googleplex.com/builds/pending/P4481738/test_suites_x86_64_fastbuild3d_linux/latest

SKIPPED: Tests were skipped for git_master/gce_x86_phone-userdebug_fastbuild3c_linux/4125040 (ToT). Internal error: cannot find a successful build output for target gce_x86_phone-userdebug_fastbuild3c_linux

SKIPPED: Tests were skipped for git_master/gce_x86_phone-userdebug_fastbuild3c_linux/4125040 (ToT). Internal error: cannot find a successful build output for target gce_x86_phone-userdebug_fastbuild3c_linux

SKIPPED: Tests were skipped for git_master/gce_x86_phone-userdebug_fastbuild3c_linux/4125040 (ToT). Internal error: cannot find a successful build output for target gce_x86_phone-userdebug_fastbuild3c_linux

SKIPPED: Tests were skipped for git_master/gce_x86_phone-userdebug_fastbuild3c_linux/4125040 (ToT). Internal error: cannot find a successful build output for target gce_x86_phone-userdebug_fastbuild3c_linux

SKIPPED: Tests were skipped for git_master/gce_x86_phone-userdebug_fastbuild3c_linux/4125040 (ToT). Internal error: cannot find a successful build output for target gce_x86_phone-userdebug_fastbuild3c_linux

SKIPPED: Tests were skipped for git_master/gce_x86_phone-userdebug_fastbuild3c_linux/4125040 (ToT). Internal error: cannot find a successful build output for target gce_x86_phone-userdebug_fastbuild3c_linux

SKIPPED: Tests were skipped for git_master/gce_x86_phone-userdebug_fastbuild3c_linux/4125040 (ToT). Internal error: cannot find a successful build output for target gce_x86_phone-userdebug_fastbuild3c_linux

SKIPPED: Tests were skipped for git_master/gce_x86_phone-userdebug_fastbuild3c_linux/4125040 (ToT). Internal error: cannot find a successful build output for target gce_x86_phone-userdebug_fastbuild3c_linux

SKIPPED: Tests were skipped for git_master/gce_x86_phone-userdebug_fastbuild3c_linux/4125040 (ToT). Internal error: cannot find a successful build output for target gce_x86_phone-userdebug_fastbuild3c_linux

SKIPPED: Tests were skipped for git_master/gce_x86_phone-userdebug_fastbuild3c_linux/4125040 (ToT). Internal error: cannot find a successful build output for target gce_x86_phone-userdebug_fastbuild3c_linux


=== git_master/sailfish-userdebug_fastbuild3_linux ===

CONFLICT: Your changes failed to cherry-pick against build 4125040 (could not apply 0169376... Clean up Predicate related code in android.test). See logs/git.log in https://android-build.googleplex.com/builds/pending/P4481734/sailfish-userdebug_fastbuild3_linux/latest. NOTE: This build has automerged changes. You may need to perform a manual  merge. See http://go/automerger-presubmit-faq. 
Note: This is a checkbuild (go/checkbuild). It will take longer and could uncover errors not found in other builds.


===

Have a question? Found a bug? http://go/treehugger-troubleshoot

Patch-set: 3
Tag: autogenerated:TreeHugger:Verify-Fail
Reviewer: Gerrit User 1062513 <1062513@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Presubmit-Verified=-1