Update patch set 11
Patch Set 11:

I was expecting this but this was building locally. Probably this change has been merged after my last sync


frameworks/opt/net/wifi/service/java/com/android/server/wifi/MemoryStoreImpl.java:141: error: cannot find symbol
mIpMemoryStore = (IpMemoryStore) mContext.getSystemService(Context.IP_MEMORY_STORE_SERVICE);
^
symbol: variable IP_MEMORY_STORE_SERVICE
location: class Context
1 error

Patch-set: 11
Reviewer: Gerrit User 1015428 <1015428@85c56323-6fa9-3386-8a01-6480fb634889>