Switch to C++20
Prepare for using std::array<> and std::span<> in headers included from
this library. Remove the AFont constructors to prevent that the build
fails as follows:

frameworks/base/native/android/system_fonts.cpp:265:35: error: no matching member function for call to 'insert'
                            fonts.insert(
                            ~~~~~~^~~~~~

Change-Id: I384d05f5d3e471f8f58294119d04eb8ab16697ba
Signed-off-by: Bart Van Assche <bvanassche@google.com>