am:double check the  association object to fix the potential NPE problem.
The crash log:
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.android.internal.app.procstats.AssociationState$SourceState.trackProcState(int, int, long)' on a null object reference
at com.android.server.am.ContentProviderConnection.trackProcState(ContentProviderConnection.java:123)
at com.android.server.am.OomAdjuster.computeProviderHostOomAdjLSP(OomAdjuster.java:3350)
at com.android.server.am.ContentProviderConnection.computeHostOomAdjLSP(ContentProviderConnection.java:81)
at com.android.server.am.OomAdjusterModernImpl$ComputeConnectionIgnoringReachableClientsConsumer.accept(OomAdjusterModernImpl.java:691)
at com.android.server.am.OomAdjusterModernImpl$ComputeConnectionIgnoringReachableClientsConsumer.accept(OomAdjusterModernImpl.java:665)
at com.android.server.am.OomAdjusterModernImpl.forEachClientConnectionLSP(OomAdjusterModernImpl.java:1261)
at com.android.server.am.OomAdjusterModernImpl.computeOomAdjIgnoringReachablesLSP(OomAdjusterModernImpl.java:1169)
.......

This problem happen due to concurrent execution of stopAssociation and trackProcState methods by multiple threads.The stopAssociation method is not need to add double check,This is because this method is the only place where the association object is assigned to null.

Test: OEM monkey test
Bug: 373519351
Change-Id: I2fbd479a7f73b7e194af6031070c8a7ed8a63c14