Update patch set 5
Patch Set 5:

I added a simple test to check if the transport in TRANSPORT_NAMES are under the range of MIN_TRANSPORT to MAX_TRANSPORT.
But I got the "java.lang.IllegalAccessError" like below and I don't know why.
Does anyone know what's going on?
Am I missing something?

Log:
STACKTRACE:
java.lang.IllegalAccessError: Field 'android.net.NetworkCapabilities.TRANSPORT_NAMES' is inaccessible to class 'android.net.NetworkCapabilitiesTest' (declaration of 'android.net.NetworkCapabilitiesTest' appears in /data/app/com.android.frameworks.tests.net-XSAsLBZjzK7ID-4L0PdTZw==/base.apk)
	at android.net.NetworkCapabilitiesTest.testGetTransportName(NetworkCapabilitiesTest.java:603)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:52)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:148)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:142)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:921)

Patch-set: 5
Reviewer: Gerrit User 1308163 <1308163@85c56323-6fa9-3386-8a01-6480fb634889>