Update patch set 1
Patch Set 1:

We encountered the following problem，when the First Toast occurs ADD_DUPLICATE_ADD error

java.lang.IllegalStateException: View android.widget.LinearLayout
{f0dc1a3 V.E...... ......ID 0,0-635,119}
has already been added to the window manager.
at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:331)
at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:94)
at android.widget.Toast$TN.handleShow(Toast.java:500)
at android.widget.Toast$TN$1.handleMessage(Toast.java:404)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:164)
at com.android.server.SystemServer.run(SystemServer.java:455)
at com.android.server.SystemServer.main(SystemServer.java:288)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:518)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:801)

Patch-set: 1
Reviewer: Gerrit User 1006497 <1006497@85c56323-6fa9-3386-8a01-6480fb634889>
Reviewer: Gerrit User 1003338 <1003338@85c56323-6fa9-3386-8a01-6480fb634889>
Reviewer: Gerrit User 1057059 <1057059@85c56323-6fa9-3386-8a01-6480fb634889>
Reviewer: Gerrit User 1062513 <1062513@85c56323-6fa9-3386-8a01-6480fb634889>
Reviewer: Gerrit User 1290647 <1290647@85c56323-6fa9-3386-8a01-6480fb634889>