Update patch set 3
Patch Set 3: Fails

This is an automated message from the Deckard Autoverifier:

This patchset fails to build in the public AOSP source tree.  The following snippet of output from `make` may point you in the right direction:

packages/apps/Phone/src/com/android/phone/PhoneInterfaceManager.java:49: com.android.phone.PhoneInterfaceManager is not abstract and does not override abstract method sendDtmf(java.lang.String,char) in com.android.internal.telephony.ITelephony
public class PhoneInterfaceManager extends ITelephony.Stub {
       ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error
make: *** [out/target/common/obj/APPS/Phone_intermediates/classes-full-debug.jar] Error 41

If your patchset has a dependency in a separate project and you believe that this is the cause of the breakage, a reviewer can verify +1 and Deckard will remove the verify -1 shortly thereafter.

Otherwise, if you wish to pursue this change, please fix the error and upload a new patchset.

Thanks!

Patch-set: 3
Label: Code-Review=0