Update patch set 1
Patch Set 1: Fails

The code is impressively clean and seems to follow the style guide to the letter, which is very much appreciated.

Unfortunately, this change fails to build, it might be missing an import.

frameworks/base/voip/java/com/android/server/sip/SipHelper.java:115: cannot find symbol
symbol  : variable SipFeature
location: class com.android.server.sip.SipHelper
        String methods = SipFeature.getAllowedMethods();

The entire sequence of 4 changes builds fine, so this might simply require to move a line from one change to the other.

Patch-set: 1
Label: Code-Review=0