Update patch set 1
Patch Set 1: Fails; No score

Unfortunately this code no longer compiles against the latest master:

frameworks/base/libs/audioflinger/AudioHardwareOss.cpp: In function 'android::AudioHardwareInterface* android::createAudioHardware()':
frameworks/base/libs/audioflinger/AudioHardwareOss.cpp:449: error: cannot allocate an object of abstract type 'android::AudioHardwareOss'
frameworks/base/libs/audioflinger/AudioHardwareOss.h:88: note:   because the following virtual functions are pure within 'android::AudioHardwareOss':
hardware/libhardware_legacy/include/hardware_legacy/AudioHardwareInterface.h:218: note: 	virtual android::AudioStreamIn* android::AudioHardwareInterface::openInputStream(int, int, int, uint32_t, android::status_t*, android::AudioSystem::audio_in_acoustics)

If the change is still relevant, please fix that issue and upload a replacement.

Patch-set: 1
Reviewer: Gerrit User 1000660 <1000660@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Code-Review=0
Label: Verified=-1