Fix screen frozen caused NPE issue
If display removal happens during screen freezing, the referring
DisplayContent is null, NPE happens.

We should stop freeze before display has been removed.

The crash info is as follows:

AndroidRuntime:
*** FATAL EXCEPTION IN SYSTEM PROCESS: android.display
java.lang.NullPointerException: Attempt to invoke virtual method 'int com.android.server.wm.DisplayContent.getOrientation()' on a null object reference
       at com.android.server.wm.WindowManagerService.updateOrientationFromAppTokensLocked(WindowManagerService.java:2461)
       at com.android.server.wm.WindowManagerService.updateOrientationFromAppTokensLocked(WindowManagerService.java:2454)
       at com.android.server.wm.WindowManagerService.stopFreezingDisplayLocked(WindowManagerService.java:5894)
       at com.android.server.wm.AppWindowToken.stopFreezingScreen(AppWindowToken.java:1165)
       at com.android.server.wm.AppWindowToken.onAppFreezeTimeout(AppWindowToken.java:1172)
       at com.android.server.wm.WindowManagerService$H.handleMessage(WindowManagerService.java:4816)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:193)
       at android.os.HandlerThread.run(HandlerThread.java:65)
       at com.android.server.ServiceThread.run(ServiceThread.java:44)