Update patch set 2
Patch Set 2: Code-Review-2

Looks like this breaks CTS with:

======
[1/8] com.android.cts.net.HostsideVpnTests#testDefault: FAILED (18.084s)

STACKTRACE:
java.lang.AssertionError: on-device tests failed:
com.android.cts.net.hostside.VpnTest#testDefault:
junit.framework.AssertionFailedError: Socket opened before VPN connects should be closed when VPN connects
======

Perhaps the changes to closeSocketsForFirewallChainLocked are not correct.

Patch-set: 2
Reviewer: Gerrit User 1000835 <1000835@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Code-Review=-2