Update patch set 2
Patch Set 2: Verified-1

This is an automated message from the Deckard Autoverifier.

Patchset merges but does not build in AOSP.
The following snippet of `make` output may point you in the right direction:

  frameworks/base/packages/SystemUI/src/com/android/systemui/statusbar/policy/SIMHelper.java:27: cannot find symbol
symbol  : class SubscriptionController
location: package android.telephony
import android.telephony.SubscriptionController;
                        ^
frameworks/base/packages/SystemUI/src/com/android/systemui/statusbar/policy/SIMHelper.java:28: package android.telephony.SubscriptionController does not exist
import android.telephony.SubscriptionController.SubInfoRecord;
                                               ^
frameworks/base/packages/SystemUI/src/com/android/systemui/statusbar/policy/SIMHelper.java:45: package SubscriptionController does not exist
...


If your patchset has a dependency in a separate project, please ensure that
both changes are uploaded with the same Change-Id.

Patch-set: 2
Label: Verified=-1