IllegalStateException: Have not received sensor event when getDeviceStateInfoLocked is being called
Bug:00000000
Test: 1.Cycle restart device
```
while(true)
do
    adb reboot
    sleep 200
done
```
2.adb shell logcat -b all | grep "IllegalStateException"
Change-Id: I9183b424027d2f34bc9bdaf11a7edc1ca10eeadb
Signed-off-by: huyuxin <huyuxin@xiaomi.com>