Update patch set 2
Patch Set 2: Presubmit-Ready+1

I looked at one of the failures; e.g. marlin debug: https://android-build.googleplex.com/builds/pending/P6505254/marlin-userdebug/latest/view/logs/build_error.log

It's this:

/mnt/disks/build-disk/src/googleplex-android/master/frameworks/base/telephony/java/android/telephony/data/ApnSetting.java:82: error: Field android.telephony.data.ApnSetting.TYPE_DEFAULT has changed value from 17 to 1 [ChangedValue]

Which means it doesn't have the metalava change yet. Even though it was merged into AOSP around 5pm it looks like it got automerged into internal master right before 10pm, and since it wasn't in this topic, it didn't get pulled along with the other two CLs.

Anyway, it should be there now so I'm retrying this topic:

Patch-set: 2
Reviewer: Gerrit User 1004689 <1004689@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Presubmit-Ready=+1