Fix pointerIndex out of range at nativeGetAxisValue
Since findPointerIndex can return -1 there should be a
guard statement here.

This change follows the pattern for MotionEvent.ACTION_MOVE
elsewhere in this file.

Typical stack when error occurs:

  java.lang.IllegalArgumentException: pointerIndex out of range
  at android.view.MotionEvent.nativeGetAxisValue(Native Method)
  at android.view.MotionEvent.getY(MotionEvent.java:1998)
  at com.android.systemui.statusbar.stack.NotificationStackScrollLayout.onScrollTouch(NotificationStackScrollLayout.java:868)
  at com.android.systemui.statusbar.stack.NotificationStackScrollLayout.onTouchEvent(NotificationStackScrollLayout.java:724)
  at android.view.View.dispatchTouchEvent(View.java:8464)
  ...

Change-Id: Ia3141c10de084b0ed8f81e632f3b0bc6573ca64e