Update patch set 11
Patch Set 11:

DataIntegrityCheckerTest.testIntegrityWithoutUpdate (com.android.server.wifi.util) 	00.039
 java.lang.Exception: Unexpected exception, expected<java.security.DigestException> but was<java.lang.RuntimeException>
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:28)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:148)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:142)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.RuntimeException: failed to set system property
	at android.os.SystemProperties.native_set(Native Method)
	at android.os.SystemProperties.set(SystemProperties.java:195)
	at com.android.server.wifi.util.DataIntegrityChecker.reportException(DataIntegrityChecker.java:327)
	at com.android.server.wifi.util.DataIntegrityChecker.readIntegrityData(DataIntegrityChecker.java:294)
	at com.android.server.wifi.util.DataIntegrityChecker.isOk(DataIntegrityChecker.java:140)
	at com.android.server.wifi.util.DataIntegrityCheckerTest.testIntegrityWithoutUpdate(DataIntegrityCheckerTest.java:82)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:52)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:19)
	... 4 more

Patch-set: 11
Reviewer: Gerrit User 1352498 <1352498@85c56323-6fa9-3386-8a01-6480fb634889>