Update patch set 1
Patch Set 1: Verified-1

This is an automated message from the Deckard Autoverifier.

Patchset merges but does not build in AOSP.
The following snippet of `make` output may point you in the right direction:

  frameworks/base/packages/SystemUI/src/com/android/systemui/statusbar/policy/SIMHelper.java:27: cannot find symbol
symbol  : class SimInfoManager
location: package android.telephony
import android.telephony.SimInfoManager;
                        ^
frameworks/base/packages/SystemUI/src/com/android/systemui/statusbar/policy/SIMHelper.java:28: package android.telephony.SimInfoManager does not exist
import android.telephony.SimInfoManager.SimInfoRecord;
                                       ^
frameworks/base/packages/SystemUI/src/com/android/systemui/statusbar/policy/SIMHelper.java:45: package SimInfoManager does not exist
...


If your patchset has a dependency in a separate project, please ensure that
both changes are uploaded with the same Change-Id.

Patch-set: 1
Label: Verified=-1