Don't validate apex install for multipackage session
This fix a fatal crash issue as below, for multipackage
session whose 'stageDir' is null.

java.lang.NullPointerException: Attempt to invoke virtual
method 'java.lang.String[] java.io.File.list()' on a null object reference
at PackageInstallerSession.getNamesLocked(PackageInstallerSession.java:838)
at PackageInstallerSession.getAddedApksLocked(PackageInstallerSession.java:875)
at validateApexInstallLocked(PackageInstallerSession.java:2116)
at PackageInstallerSession.onAfterSessionRead(PackageInstallerSession.java:1761)
at PackageInstallerService.readSessionsLocked(PackageInstallerService.java:447)
at PackageInstallerService.systemReady(PackageInstallerService.java:261)
at PackageManagerService.systemReady(PackageManagerService.java:22076)
at com.android.server.SystemServer.startOtherServices(SystemServer.java:2359)
at com.android.server.SystemServer.run(SystemServer.java:665)
at com.android.server.SystemServer.main(SystemServer.java:481)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:945)

Bug: 176400973
Test: atest StagedInstallTest#testInstallMultipleStagedApex

Signed-off-by: liulvping <liulvping@xiaomi.com>
Change-Id: I5c08c269dd3d9bda3aeec22712314ca030a78e84