The value returned by mNotificationList.size() is out of synchronize
CTS android.app.cts.NotificationManagerTest#testCancel may have
below exception
java.lang.IndexOutOfBoundsException: Invalid index 2, size is 2
   at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayL
        ist.java:255)
   at java.util.ArrayList.get(ArrayList.java:308)
   at com.android.server.notification.NotificationManagerServic
        e$5.getAppActiveNotifications(NotificationManagerServic
        e.java:1297)
   at android.app.INotificationManager$Stub.onTransact(INotific
        ationManager.java:611)
   at android.os.Binder.execTransact(Binder.java:453)
Need to synchronize the access of mNotificationList.size(),
which may be changed in cancelNotification asynchronously

Change-Id: I6153a7058213279550e0eea1335f568266b9f929
Signed-off-by: guoyin.chen <guoyin.chen@freescale.com>